name: Hank

on: h

jobs: 
  jobOne:
    name: jobOneName
    needs: [job, dakwda]
    permissions: 
      actions: read
      checks: write
      id-token: write
    if: hello
    uses: random/dawda
    with:
        elixir-version: '1.10.3' 
        otp-version: '22.3' 
    secrets:
      access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} 
      password: helloworld
    runs-on: [self-hosted, linux]


env: 
  Happy: fsaf
  Yolo: false

defaults: 
  run:
    working-directory: scripts
    shell: python

concurrency: 
  group: hello
  cancel-in-progress: true