name: Hank

on: 
  check_run:
    types: [requested]
  check_suite:
    
jobs:
  jobOne:
    name: jobby
    needs: jobThre
  jobTwo:
    name: joker
    needs: [jobOne, jobThree]
  jobThree:
    needs: jobTwo
