name: Hank

on: 
  check_run:
    types: [requested]
  check_suite:
    
  # check_suite:
  # check_run:
  #   types: [rerequested, completed]

jobs:
  

defaults:
  run: 
    shell: bash
    working-directory: scripts

concurrency: 
  cancel-in-progress: true
  group: staging_environment
